//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 

namespace Reporter.XsdClasses.OnNschfdoppokUtd970
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлДокумент документField;

        private string идФайлField;

        private ФайлВерсФорм версФормField;

        private string версПрогField;

        /// <remarks/>
        public ФайлДокумент Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументИдИнфПрод идИнфПродField;

        private ФайлДокументСодФХЖ4 содФХЖ4Field;

        private ФайлДокументИнфПокЗаГоскКазн инфПокЗаГоскКазнField;

        private ФайлДокументПодписант[] подписантField;

        private РеквДокТип оснДоверОргСостField;

        private ФайлДокументКНД кНДField;

        private string уИДField;

        private string датаИнфПокField;

        private string времИнфПокField;

        private string наимЭконСубСостField;

        /// <remarks/>
        public ФайлДокументИдИнфПрод ИдИнфПрод
        {
            get
            {
                return this.идИнфПродField;
            }
            set
            {
                this.идИнфПродField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСодФХЖ4 СодФХЖ4
        {
            get
            {
                return this.содФХЖ4Field;
            }
            set
            {
                this.содФХЖ4Field = value;
            }
        }

        /// <remarks/>
        public ФайлДокументИнфПокЗаГоскКазн ИнфПокЗаГоскКазн
        {
            get
            {
                return this.инфПокЗаГоскКазнField;
            }
            set
            {
                this.инфПокЗаГоскКазнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант")]
        public ФайлДокументПодписант[] Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        public РеквДокТип ОснДоверОргСост
        {
            get
            {
                return this.оснДоверОргСостField;
            }
            set
            {
                this.оснДоверОргСостField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УИД
        {
            get
            {
                return this.уИДField;
            }
            set
            {
                this.уИДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИнфПок
        {
            get
            {
                return this.датаИнфПокField;
            }
            set
            {
                this.датаИнфПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремИнфПок
        {
            get
            {
                return this.времИнфПокField;
            }
            set
            {
                this.времИнфПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЭконСубСост
        {
            get
            {
                return this.наимЭконСубСостField;
            }
            set
            {
                this.наимЭконСубСостField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументИдИнфПрод
    {

        private string[] эпField;

        private string идФайлИнфПрField;

        private string датаФайлИнфПрField;

        private string времФайлИнфПрField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЭП")]
        public string[] ЭП
        {
            get
            {
                return this.эпField;
            }
            set
            {
                this.эпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПр
        {
            get
            {
                return this.идФайлИнфПрField;
            }
            set
            {
                this.идФайлИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаФайлИнфПр
        {
            get
            {
                return this.датаФайлИнфПрField;
            }
            set
            {
                this.датаФайлИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремФайлИнфПр
        {
            get
            {
                return this.времФайлИнфПрField;
            }
            set
            {
                this.времФайлИнфПрField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИнНеУчТип
    {

        private СвИнНеУчТипИдСтат идСтатField;

        private string кодСтрField;

        private string наимСтранField;

        private string наимField;

        private string идентифField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СвИнНеУчТипИдСтат ИдСтат
        {
            get
            {
                return this.идСтатField;
            }
            set
            {
                this.идСтатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр
        {
            get
            {
                return this.кодСтрField;
            }
            set
            {
                this.кодСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтран
        {
            get
            {
                return this.наимСтранField;
            }
            set
            {
                this.наимСтранField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Наим
        {
            get
            {
                return this.наимField;
            }
            set
            {
                this.наимField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get
            {
                return this.идентифField;
            }
            set
            {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum СвИнНеУчТипИдСтат
    {

        /// <remarks/>
        ИО,

        /// <remarks/>
        ИГ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ИдРекСостТип
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДаннИно", typeof(СвИнНеУчТип))]
        [System.Xml.Serialization.XmlElementAttribute("ИННФЛ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ИННЮЛ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("НаимОИВ", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        ДаннИно,

        /// <remarks/>
        ИННФЛ,

        /// <remarks/>
        ИННЮЛ,

        /// <remarks/>
        НаимОИВ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class РеквДокТип
    {

        private ИдРекСостТип[] реквИдРекСостField;

        private string реквНаимДокField;

        private string реквНомерДокField;

        private string реквДатаДокField;

        private string реквИдФайлДокField;

        private string реквИдДокField;

        private string рИдСистХранДField;

        private string реквУРЛСистДокField;

        private string реквДопСведДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РеквИдРекСост")]
        public ИдРекСостТип[] РеквИдРекСост
        {
            get
            {
                return this.реквИдРекСостField;
            }
            set
            {
                this.реквИдРекСостField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквНаимДок
        {
            get
            {
                return this.реквНаимДокField;
            }
            set
            {
                this.реквНаимДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквНомерДок
        {
            get
            {
                return this.реквНомерДокField;
            }
            set
            {
                this.реквНомерДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквДатаДок
        {
            get
            {
                return this.реквДатаДокField;
            }
            set
            {
                this.реквДатаДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквИдФайлДок
        {
            get
            {
                return this.реквИдФайлДокField;
            }
            set
            {
                this.реквИдФайлДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквИдДок
        {
            get
            {
                return this.реквИдДокField;
            }
            set
            {
                this.реквИдДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РИдСистХранД
        {
            get
            {
                return this.рИдСистХранДField;
            }
            set
            {
                this.рИдСистХранДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквУРЛСистДок
        {
            get
            {
                return this.реквУРЛСистДокField;
            }
            set
            {
                this.реквУРЛСистДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РеквДопСведДок
        {
            get
            {
                return this.реквДопСведДокField;
            }
            set
            {
                this.реквДопСведДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4
    {

        private ФайлДокументСодФХЖ4СвПрин свПринField;

        private ФайлДокументСодФХЖ4ИнфПолФХЖ4 инфПолФХЖ4Field;

        private string наимДокОпрПрField;

        private string функцияField;

        private string порНомДокИнфПрField;

        private string датаДокИнфПрField;

        private string видОперField;

        /// <remarks/>
        public ФайлДокументСодФХЖ4СвПрин СвПрин
        {
            get
            {
                return this.свПринField;
            }
            set
            {
                this.свПринField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСодФХЖ4ИнфПолФХЖ4 ИнфПолФХЖ4
        {
            get
            {
                return this.инфПолФХЖ4Field;
            }
            set
            {
                this.инфПолФХЖ4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОпрПр
        {
            get
            {
                return this.наимДокОпрПрField;
            }
            set
            {
                this.наимДокОпрПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Функция
        {
            get
            {
                return this.функцияField;
            }
            set
            {
                this.функцияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПорНомДокИнфПр
        {
            get
            {
                return this.порНомДокИнфПрField;
            }
            set
            {
                this.порНомДокИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаДокИнфПр
        {
            get
            {
                return this.датаДокИнфПрField;
            }
            set
            {
                this.датаДокИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидОпер
        {
            get
            {
                return this.видОперField;
            }
            set
            {
                this.видОперField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПрин
    {

        private ФайлДокументСодФХЖ4СвПринКодСодОпер кодСодОперField;

        private ФайлДокументСодФХЖ4СвПринСвЛицПрин свЛицПринField;

        private string содОперField;

        private string датаПринField;

        /// <remarks/>
        public ФайлДокументСодФХЖ4СвПринКодСодОпер КодСодОпер
        {
            get
            {
                return this.кодСодОперField;
            }
            set
            {
                this.кодСодОперField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСодФХЖ4СвПринСвЛицПрин СвЛицПрин
        {
            get
            {
                return this.свЛицПринField;
            }
            set
            {
                this.свЛицПринField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СодОпер
        {
            get
            {
                return this.содОперField;
            }
            set
            {
                this.содОперField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПрин
        {
            get
            {
                return this.датаПринField;
            }
            set
            {
                this.датаПринField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринКодСодОпер
    {

        private РеквДокТип реквДокРасхField;

        private ФайлДокументСодФХЖ4СвПринКодСодОперКодИтога кодИтогаField;

        /// <remarks/>
        public РеквДокТип РеквДокРасх
        {
            get
            {
                return this.реквДокРасхField;
            }
            set
            {
                this.реквДокРасхField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументСодФХЖ4СвПринКодСодОперКодИтога КодИтога
        {
            get
            {
                return this.кодИтогаField;
            }
            set
            {
                this.кодИтогаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументСодФХЖ4СвПринКодСодОперКодИтога
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринСвЛицПрин
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнЛицо", typeof(ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицо))]
        [System.Xml.Serialization.XmlElementAttribute("РабОргПок", typeof(ФайлДокументСодФХЖ4СвПринСвЛицПринРабОргПок))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицо
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПредОргПрин", typeof(ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицоПредОргПрин))]
        [System.Xml.Serialization.XmlElementAttribute("ФЛПрин", typeof(ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицоФЛПрин))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицоПредОргПрин
    {

        private РеквДокТип оснДоверОргПринField;

        private РеквДокТип оснПолнПредПринField;

        private ФИОТип фИОField;

        private string должностьField;

        private string иныеСведField;

        private string наимОргПринField;

        private string иННОргПринField;

        /// <remarks/>
        public РеквДокТип ОснДоверОргПрин
        {
            get
            {
                return this.оснДоверОргПринField;
            }
            set
            {
                this.оснДоверОргПринField = value;
            }
        }

        /// <remarks/>
        public РеквДокТип ОснПолнПредПрин
        {
            get
            {
                return this.оснПолнПредПринField;
            }
            set
            {
                this.оснПолнПредПринField = value;
            }
        }

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргПрин
        {
            get
            {
                return this.наимОргПринField;
            }
            set
            {
                this.наимОргПринField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННОргПрин
        {
            get
            {
                return this.иННОргПринField;
            }
            set
            {
                this.иННОргПринField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринСвЛицПринИнЛицоФЛПрин
    {

        private РеквДокТип оснДоверФЛField;

        private ФИОТип фИОField;

        private string иННФЛПринField;

        private string иныеСведField;

        /// <remarks/>
        public РеквДокТип ОснДоверФЛ
        {
            get
            {
                return this.оснДоверФЛField;
            }
            set
            {
                this.оснДоверФЛField = value;
            }
        }

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛПрин
        {
            get
            {
                return this.иННФЛПринField;
            }
            set
            {
                this.иННФЛПринField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4СвПринСвЛицПринРабОргПок
    {

        private ФИОТип фИОField;

        private string должностьField;

        private string иныеСведField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4ИнфПолФХЖ4
    {

        private ФайлДокументСодФХЖ4ИнфПолФХЖ4ТекстИнф[] текстИнфField;

        private string идФайлИнфПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ФайлДокументСодФХЖ4ИнфПолФХЖ4ТекстИнф[] ТекстИнф
        {
            get
            {
                return this.текстИнфField;
            }
            set
            {
                this.текстИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол
        {
            get
            {
                return this.идФайлИнфПолField;
            }
            set
            {
                this.идФайлИнфПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСодФХЖ4ИнфПолФХЖ4ТекстИнф
    {

        private string идентифField;

        private string значенField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get
            {
                return this.идентифField;
            }
            set
            {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен
        {
            get
            {
                return this.значенField;
            }
            set
            {
                this.значенField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументИнфПокЗаГоскКазн
    {

        private ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбяз[] инфСведДенОбязField;

        private string идКодЗакField;

        private string лицСчетПокField;

        private string наимФинОргПокField;

        private string номРеестрЗапПокField;

        private string учНомБюдОбязПокField;

        private string кодКазначПокField;

        private string наимКазначПокField;

        private string оКТМОПокField;

        private string оКТМОМесПостField;

        private string датаОплПредField;

        private string учНомДенОбязField;

        private string очерПлатField;

        private ФайлДокументИнфПокЗаГоскКазнВидПлат видПлатField;

        private bool видПлатFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфСведДенОбяз")]
        public ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбяз[] ИнфСведДенОбяз
        {
            get
            {
                return this.инфСведДенОбязField;
            }
            set
            {
                this.инфСведДенОбязField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдКодЗак
        {
            get
            {
                return this.идКодЗакField;
            }
            set
            {
                this.идКодЗакField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЛицСчетПок
        {
            get
            {
                return this.лицСчетПокField;
            }
            set
            {
                this.лицСчетПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимФинОргПок
        {
            get
            {
                return this.наимФинОргПокField;
            }
            set
            {
                this.наимФинОргПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомРеестрЗапПок
        {
            get
            {
                return this.номРеестрЗапПокField;
            }
            set
            {
                this.номРеестрЗапПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УчНомБюдОбязПок
        {
            get
            {
                return this.учНомБюдОбязПокField;
            }
            set
            {
                this.учНомБюдОбязПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодКазначПок
        {
            get
            {
                return this.кодКазначПокField;
            }
            set
            {
                this.кодКазначПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимКазначПок
        {
            get
            {
                return this.наимКазначПокField;
            }
            set
            {
                this.наимКазначПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМОПок
        {
            get
            {
                return this.оКТМОПокField;
            }
            set
            {
                this.оКТМОПокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМОМесПост
        {
            get
            {
                return this.оКТМОМесПостField;
            }
            set
            {
                this.оКТМОМесПостField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОплПред
        {
            get
            {
                return this.датаОплПредField;
            }
            set
            {
                this.датаОплПредField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УчНомДенОбяз
        {
            get
            {
                return this.учНомДенОбязField;
            }
            set
            {
                this.учНомДенОбязField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОчерПлат
        {
            get
            {
                return this.очерПлатField;
            }
            set
            {
                this.очерПлатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументИнфПокЗаГоскКазнВидПлат ВидПлат
        {
            get
            {
                return this.видПлатField;
            }
            set
            {
                this.видПлатField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ВидПлатSpecified
        {
            get
            {
                return this.видПлатFieldSpecified;
            }
            set
            {
                this.видПлатFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбяз
    {

        private string номСтрField;

        private string кодОбъектФАИПField;

        private ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбязВидСредств видСредствField;

        private string кодПокБюджКлассField;

        private string кодЦелиПокупField;

        private decimal сумАвансField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомСтр
        {
            get
            {
                return this.номСтрField;
            }
            set
            {
                this.номСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОбъектФАИП
        {
            get
            {
                return this.кодОбъектФАИПField;
            }
            set
            {
                this.кодОбъектФАИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбязВидСредств ВидСредств
        {
            get
            {
                return this.видСредствField;
            }
            set
            {
                this.видСредствField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодПокБюджКласс
        {
            get
            {
                return this.кодПокБюджКлассField;
            }
            set
            {
                this.кодПокБюджКлассField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодЦелиПокуп
        {
            get
            {
                return this.кодЦелиПокупField;
            }
            set
            {
                this.кодЦелиПокупField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СумАванс
        {
            get
            {
                return this.сумАвансField;
            }
            set
            {
                this.сумАвансField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументИнфПокЗаГоскКазнИнфСведДенОбязВидСредств
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументИнфПокЗаГоскКазнВидПлат
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private ФИОТип фИОField;

        private object[] itemsField;

        private string должнField;

        private ФайлДокументПодписантТипПодпис типПодписField;

        private bool типПодписFieldSpecified;

        private string датаПодДокField;

        private ФайлДокументПодписантСпосПодтПолном спосПодтПолномField;

        private string допСведПодпField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвДоверБум", typeof(ФайлДокументПодписантСвДоверБум))]
        [System.Xml.Serialization.XmlElementAttribute("СвДоверЭл", typeof(ФайлДокументПодписантСвДоверЭл))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн
        {
            get
            {
                return this.должнField;
            }
            set
            {
                this.должнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантТипПодпис ТипПодпис
        {
            get
            {
                return this.типПодписField;
            }
            set
            {
                this.типПодписField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ТипПодписSpecified
        {
            get
            {
                return this.типПодписFieldSpecified;
            }
            set
            {
                this.типПодписFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПодДок
        {
            get
            {
                return this.датаПодДокField;
            }
            set
            {
                this.датаПодДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументПодписантСпосПодтПолном СпосПодтПолном
        {
            get
            {
                return this.спосПодтПолномField;
            }
            set
            {
                this.спосПодтПолномField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопСведПодп
        {
            get
            {
                return this.допСведПодпField;
            }
            set
            {
                this.допСведПодпField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантСвДоверБум
    {

        private ФИОТип фИОField;

        private string датаВыдДоверField;

        private string внНомДоверField;

        private string свИдДоверField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаВыдДовер
        {
            get
            {
                return this.датаВыдДоверField;
            }
            set
            {
                this.датаВыдДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВнНомДовер
        {
            get
            {
                return this.внНомДоверField;
            }
            set
            {
                this.внНомДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвИдДовер
        {
            get
            {
                return this.свИдДоверField;
            }
            set
            {
                this.свИдДоверField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантСвДоверЭл
    {

        private string номДоверField;

        private string датаВыдДоверField;

        private string внНомДоверField;

        private string датаВнРегДоверField;

        private string идСистХранField;

        private string уРЛСистField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомДовер
        {
            get
            {
                return this.номДоверField;
            }
            set
            {
                this.номДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаВыдДовер
        {
            get
            {
                return this.датаВыдДоверField;
            }
            set
            {
                this.датаВыдДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВнНомДовер
        {
            get
            {
                return this.внНомДоверField;
            }
            set
            {
                this.внНомДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаВнРегДовер
        {
            get
            {
                return this.датаВнРегДоверField;
            }
            set
            {
                this.датаВнРегДоверField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдСистХран
        {
            get
            {
                return this.идСистХранField;
            }
            set
            {
                this.идСистХранField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УРЛСист
        {
            get
            {
                return this.уРЛСистField;
            }
            set
            {
                this.уРЛСистField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументПодписантТипПодпис
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументПодписантСпосПодтПолном
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументКНД
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1115132")]
        Item1115132,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлВерсФорм
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.03")]
        Item503,
    }
}
