//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class DocLineItemConfiguration : EntityTypeConfiguration<DocLineItem>
    {

        public DocLineItemConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("DOC_LINE_ITEMS", "EDI");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.IdOrder)
                    .HasColumnName(@"ID_ORDER")
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.IdGood)
                    .HasColumnName(@"ID_GOOD");
            this
                .Property(p => p.IdPriceType)
                    .HasColumnName(@"ID_PRICE_TYPE");
            this
                .Property(p => p.IdDocJournal)
                    .HasColumnName(@"ID_DOC_JOURNAL")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.Gtin)
                    .HasColumnName(@"GTIN")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.BuyerCode)
                    .HasColumnName(@"BUYER_CODE")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.Description)
                    .HasColumnName(@"DESCRIPTION")
                    .HasMaxLength(512)
                    .IsUnicode(false);
            this
                .Property(p => p.Amount)
                    .HasColumnName(@"AMOUNT")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.ReqQunatity)
                    .HasColumnName(@"REQ_QUNATITY")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.UnitOfMeasure)
                    .HasColumnName(@"UNIT_OF_MEASURE")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.NetPrice)
                    .HasColumnName(@"NET_PRICE")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.NetPriceVat)
                    .HasColumnName(@"NET_PRICE_VAT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.NetAmount)
                    .HasColumnName(@"NET_AMOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.VatRate)
                    .HasColumnName(@"VAT_RATE")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.VatAmount)
                    .HasColumnName(@"VAT_AMOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.RegionIsoCode)
                    .HasColumnName(@"REGION_ISO_CODE")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.LineNumber)
                    .HasColumnName(@"LINE_NUMBER")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.OrdrspNetPrice)
                    .HasColumnName(@"ORDRSP_NET_PRICE")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.OrdrspNetPriceVat)
                    .HasColumnName(@"ORDRSP_NET_PRICE_VAT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.OrdrspNetAmount)
                    .HasColumnName(@"ORDRSP_NET_AMOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.OrdrspAmount)
                    .HasColumnName(@"ORDRSP_AMOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.OrdrspQuantity)
                    .HasColumnName(@"ORDRSP_QUANTITY")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.RecadvAcceptQuantity)
                    .HasColumnName(@"RECADV_ACCEPT_QUANTITY")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.RecadvAcceptNetPrice)
                    .HasColumnName(@"RECADV_ACCEPT_NET_PRICE")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.RecadvAcceptNetPriceVat)
                    .HasColumnName(@"RECADV_ACCEPT_NET_PRICE_VAT")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.RecadvAcceptAmount)
                    .HasColumnName(@"RECADV_ACCEPT_AMOUNT")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.RecadvAcceptNetAmount)
                    .HasColumnName(@"RECADV_ACCEPT_NET_AMOUNT")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property( p => p.IsRemoved )
                    .HasColumnName( @"IS_REMOVED" )
                    .HasMaxLength( 1 )
                    .IsUnicode( true );
            this
                .Property(p => p.Manufacturer)
                    .HasColumnName(@"MANUFACTURER")
                    .HasMaxLength(512)
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
