//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class LogOrderConfiguration : EntityTypeConfiguration<LogOrder>
    {

        public LogOrderConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("LOG_ORDERS", "EDI");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasMaxLength(38)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.IdOrder)
                    .HasColumnName(@"ID_ORDER")
                    .IsRequired()
                    .HasMaxLength(38)
                    .IsUnicode(false);
            this
                .Property(p => p.OrderStatus)
                    .HasColumnName(@"ORDER_STATUS")
                    .IsRequired();
            this
                .Property(p => p.Datetime)
                    .HasColumnName(@"DATETIME")
                    .IsRequired()
                    .HasPrecision(0);
            this
                .Property(p => p.IdDocJournal)
                    .HasColumnName(@"ID_DOC_JOURNAL");
            this
                .Property(p => p.CircilationId)
                    .HasColumnName(@"CIRCILATION_ID")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property(p => p.MessageId)
                    .HasColumnName(@"MESSAGE_ID")
                    .HasMaxLength(50)
                    .IsUnicode(true);
            this
                .Property( p => p.IdManufacturer )
                    .HasColumnName( @"ID_MANUFACTURER" );
            OnCreated();
        }

        partial void OnCreated();

    }
}
