//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class MapPriceTypeConfiguration : EntityTypeConfiguration<MapPriceType>
    {

        public MapPriceTypeConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("MAP_PRICE_TYPES", "EDI");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.GlnCompany)
                    .HasColumnName(@"GLN_COMPANY")
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.IdPriceType)
                    .HasColumnName(@"ID_PRICE_TYPE")
                    .IsRequired();
            this
                .Property(p => p.IdFilial)
                    .HasColumnName(@"ID_FILIAL");
            OnCreated();
        }

        partial void OnCreated();

    }
}
