//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt.Mapping
{

    public partial class RefBarCodeConfiguration : EntityTypeConfiguration<RefBarCode>
    {

        public RefBarCodeConfiguration()
        {
            this
                .HasKey(p => p.BarCode)
                .ToTable("REF_BAR_CODES", "ABT");
            // Properties:
            this
                .Property(p => p.IdGood)
                    .HasColumnName(@"ID_GOOD");
            this
                .Property(p => p.BarCode)
                    .HasColumnName(@"BAR_CODE")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.IsPrimary)
                    .HasColumnName(@"IS_PRIMARY");
            this
                .HasRequired(p => p.Good)
                .WithMany(r => r.BarCodes)
                .HasForeignKey(p => p.IdGood)
                .WillCascadeOnDelete(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
