//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt.Mapping
{

    public partial class RefCountryConfiguration : EntityTypeConfiguration<RefCountry>
    {

        public RefCountryConfiguration()
        {
			this
                .HasKey(p => p.Id)
                .ToTable( "REF_COUNTRIES", "ABT");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName( @"ID" )
					.IsRequired()
					.HasDatabaseGeneratedOption( System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None );
			this
				.Property( p => p.Name )
					.HasColumnName( @"NAME" )
					.HasMaxLength(100)
					.IsRequired()
					.IsUnicode( false );
			this
				.Property( p => p.Code )
					.HasColumnName( @"CODE" )
					.HasMaxLength( 3 )
					.IsUnicode( false );
			this
				.Property( p => p.NumCode )
					.HasColumnName( @"NUM_CODE" );

			OnCreated();
        }

        partial void OnCreated();

    }
}
