//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt.Mapping
{

    public partial class RefItemConfiguration : EntityTypeConfiguration<RefItem>
    {

        public RefItemConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("REF_ITEMS", "ABT");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.IdGood)
                    .HasColumnName(@"ID_GOOD");
            this
                .Property(p => p.IdName)
                    .HasColumnName(@"ID_NAME")
                    .IsRequired();
            this
                .Property(p => p.Quantity)
                    .HasColumnName(@"QUANTITY")
                    .IsRequired();
            this
                .Property(p => p.Weight)
                    .HasColumnName(@"WEIGHT")
                    .IsRequired();
            this
                .Property(p => p.Cbm)
                    .HasColumnName(@"CBM")
                    .IsRequired();
            // Associations:
            OnCreated();
        }

        partial void OnCreated();

    }
}
