//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:32:16
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class ViewInvoicHeadConfiguration : EntityTypeConfiguration<ViewInvoicHead>
    {

        public ViewInvoicHeadConfiguration()
        {
            this
                .HasKey(p => new { p.Id })
                .ToTable("VIEW_INVOIC_HEAD", "EDI");
			// Properties:
			this
				.Property( p => p.Id )
					.HasColumnName( @"ID" )
					.HasDatabaseGeneratedOption( System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None );
			this
                .Property(p => p.Barcode)
                    .HasColumnName(@"BARCODE")
                    .HasMaxLength(42)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerId)
                    .HasColumnName(@"SELLER_ID")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.SellerName)
                    .HasColumnName(@"SELLER_NAME")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerFullName)
                    .HasColumnName(@"SELLER_FULL_NAME")
                    .HasMaxLength(270)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerAddress)
                    .HasColumnName(@"SELLER_ADDRESS")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerInn)
                    .HasColumnName(@"SELLER_INN")
                    .HasMaxLength(16)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerPhone)
                    .HasColumnName(@"SELLER_PHONES")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.Director)
                    .HasColumnName(@"DIRECTOR")
                    .HasMaxLength(64)
                    .IsUnicode(false);
            this
                .Property(p => p.Accountant)
                    .HasColumnName(@"ACCOUNTANT")
                    .HasMaxLength(64)
                    .IsUnicode(false);
            this
                .Property(p => p.OldNdp)
                    .HasColumnName(@"OLD_NDP");
            this
                .Property(p => p.SellerKpp)
                    .HasColumnName(@"SELLER_KPP")
                    .HasMaxLength(16)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerOkpo)
                    .HasColumnName(@"SELLER_OKPO")
                    .HasMaxLength(16)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerPostalAddress)
                    .HasColumnName(@"SELLER_POSTAL_ADDRESS")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerCity)
                    .HasColumnName(@"SELLER_CITY")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerAccount)
                    .HasColumnName(@"SELLER_ACCOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerCorAccount)
                    .HasColumnName(@"SELLER_COR_ACCOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerBankName)
                    .HasColumnName(@"SELLER_BANK_NAME")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerBankName)
                    .HasColumnName(@"CUSTOMER_BANK_NAME")
                    .HasMaxLength(50)
                    .IsUnicode(false);
			this
				.Property( p => p.CustomerId )
					.HasColumnName( @"CUSTOMER_ID" )
					.HasDatabaseGeneratedOption( System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None );
			this
                .Property(p => p.CustomerBankCity)
                    .HasColumnName(@"CUSTOMER_BANK_CITY")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerBankCity)
                    .HasColumnName(@"SELLER_BANK_CITY")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.SellerBankSwift)
                    .HasColumnName(@"SELLER_BANK_SWIFT")
                    .HasMaxLength(9)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerName)
                    .HasColumnName(@"CUSTOMER_NAME")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.Dogovor)
                    .HasColumnName(@"DOGOVOR")
                    .HasMaxLength(508)
                    .IsUnicode(false);
            this
                .Property(p => p.NameGp)
                    .HasColumnName(@"NAME_GP")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.JuridicalAddress)
                    .HasColumnName(@"JURIDICAL_ADDRESS")
                    .HasMaxLength(4000)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerInn)
                    .HasColumnName(@"CUSTOMER_INN")
                    .HasMaxLength(16)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerPhone)
                    .HasColumnName(@"CUSTOMER_PHONES")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerKpp)
                    .HasColumnName(@"CUSTOMER_KPP")
                    .HasMaxLength(4000)
                    .IsUnicode(false);
            this
                .Property(p => p.PostalAddress)
                    .HasColumnName(@"POSTAL_ADDRESS")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerCity)
                    .HasColumnName(@"CUSTOMER_CITY")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerAccount)
                    .HasColumnName(@"CUSTOMER_ACCOUNT")
                    .HasMaxLength(4000)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerCorAccount)
                    .HasColumnName(@"CUSTOMER_COR_ACCOUNT")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerBankSwift)
                    .HasColumnName(@"CUSTOMER_BANK_SWIFT")
                    .HasMaxLength(9)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomerOkpo)
                    .HasColumnName(@"CUSTOMER_OKPO")
                    .HasMaxLength(16)
                    .IsUnicode(false);
            this
                .Property(p => p.DocDatetime)
                    .HasColumnName(@"DOC_DATETIME")
                    .HasPrecision(0);
            this
                .Property(p => p.Code)
                    .HasColumnName(@"CODE")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.TotalSumm)
                    .HasColumnName(@"TOTAL_SUMM")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.TaxSumm)
                    .HasColumnName(@"TAX_SUMM")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.TotalSummText)
                    .HasColumnName(@"TOTAL_SUMM_TEXT")
                    .HasMaxLength(4000)
                    .IsUnicode(false);
            this
                .Property(p => p.TotalCount)
                    .HasColumnName(@"TOTAL_COUNT")
                    .HasMaxLength(4000)
                    .IsUnicode(false);
            this
                .Property(p => p.PayDelay)
                    .HasColumnName(@"PAY_DELAY");
            this
                .Property(p => p.DeliveryDate)
                    .HasColumnName(@"DELIVERY_DATE")
                    .HasPrecision(0);
            this
                .Property(p => p.Storekeeper)
                    .HasColumnName(@"STOREKEEPER")
                    .HasMaxLength(128)
                    .IsUnicode(false);
			this
				.Property( p => p.StorekeeperProf )
					.HasColumnName( @"STOREKEEPER_PROF" )
					.HasMaxLength( 128 )
					.IsUnicode( false );
			this
                .Property(p => p.ZCode)
                    .HasColumnName(@"Z_CODE")
                    .HasMaxLength(135)
                    .IsUnicode(false);
            this
                .Property(p => p.Comment)
                    .HasColumnName(@"COMMENTS")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
