//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class ViewRefContractorConfiguration : EntityTypeConfiguration<ViewRefContractor>
    {

        public ViewRefContractorConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("VIEW_REF_CONTRACTORS", "EDI");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.Name)
                    .HasColumnName(@"NAME")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            this
                .Property(p => p.Address)
                    .HasColumnName(@"ADDRESS")
                    .HasMaxLength(128)
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
