//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi.Mapping
{

    public partial class ViewInvoicDetailConfiguration : EntityTypeConfiguration<ViewInvoicDetail>
    {

        public ViewInvoicDetailConfiguration()
        {
            this
                .HasKey(p => new { p.Id, p.Inbox, p.GName, p.Quantity, p.TaxRate })
                .ToTable("VIEW_INVOIC_DETAILS", "EDI");
            // Properties:
            this
                .Property(p => p.Id)
                    .HasColumnName(@"ID")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.IdDocMaster)
                    .HasColumnName(@"ID_DOC_MASTER");
            this
                .Property(p => p.Code)
                    .HasColumnName(@"CODE")
                    .HasMaxLength(32)
                    .IsUnicode(false);
            this
                .Property(p => p.IName)
                    .HasColumnName(@"I_NAME")
                    .HasMaxLength(4)
                    .IsUnicode(false);
            this
                .Property(p => p.Inbox)
                    .HasColumnName(@"INBOX")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.GName)
                    .HasColumnName(@"G_NAME")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .IsUnicode(false);
            this
                .Property(p => p.GoodSize)
                    .HasColumnName(@"GOOD_SIZE")
                    .HasMaxLength(8)
                    .IsUnicode(false);
            this
                .Property(p => p.Quantity)
                    .HasColumnName(@"QUANTITY")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.PriceWithoutTax)
                    .HasColumnName(@"PRICE_WITHOUT_TAX");
            this
                .Property(p => p.SummWithoutTax)
                    .HasColumnName(@"SUMM_WITHOUT_TAX");
            this
                .Property(p => p.Acsiz)
                    .HasColumnName(@"ACSIZ")
                    .HasMaxLength(1)
                    .IsFixedLength()
                    .IsUnicode(false);
            this
                .Property(p => p.TaxRate)
                    .HasColumnName(@"TAX_RATE")
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.TaxSumm)
                    .HasColumnName(@"TAX_SUMM");
            this
                .Property(p => p.Summ)
                    .HasColumnName(@"SUMM");
            this
                .Property(p => p.CountryName)
                    .HasColumnName(@"COUNTRY_NAME")
                    .HasMaxLength(100)
                    .IsUnicode(false);
            this
                .Property(p => p.CountryNumCode)
                    .HasColumnName(@"COUNTRY_NUM_CODE")
                    .HasMaxLength(40)
                    .IsUnicode(false);
            this
                .Property(p => p.CustomsNum)
                    .HasColumnName(@"CUSTOMS_NUM")
                    .HasMaxLength(32)
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
