//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonturEdoClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://data.nalog.ru/html/sites/www.new.nalog.ru/xsd/ON_NSCHFDOPPR_1_997_01_05_0" +
            "1_03.xsd")]
        public string XsdSchemaUrl {
            get {
                return ((string)(this["XsdSchemaUrl"]));
            }
            set {
                this["XsdSchemaUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("643")]
        public string DefaultOrgCountryCode {
            get {
                return ((string)(this["DefaultOrgCountryCode"]));
            }
            set {
                this["DefaultOrgCountryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("796")]
        public string DefaultUnit {
            get {
                return ((string)(this["DefaultUnit"]));
            }
            set {
                this["DefaultUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("643")]
        public string DefaultCurrency {
            get {
                return ((string)(this["DefaultCurrency"]));
            }
            set {
                this["DefaultCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Files")]
        public string XmlFilesPath {
            get {
                return ((string)(this["XmlFilesPath"]));
            }
            set {
                this["XmlFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Зав. складом")]
        public string DefaultEmployePosition {
            get {
                return ((string)(this["DefaultEmployePosition"]));
            }
            set {
                this["DefaultEmployePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://markirovka.crpt.ru/api/v3/true-api")]
        public string UrlAddressHonestMark {
            get {
                return ((string)(this["UrlAddressHonestMark"]));
            }
            set {
                this["UrlAddressHonestMark"] = value;
            }
        }
    }
}
