//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class ConnString
    {

        public ConnString()
        {
            OnCreated();
        }

        #region Properties

        public virtual string ConnStr { get; set; }

        public virtual string Comment { get; set; }

        #endregion
		

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
