//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt
{
    /// <summary>
    /// ?????
    /// </summary>
    public partial class DocGoodsI
    {

        public DocGoodsI()
        {
            this.DiscountRate = 0;
            this.DiscountSumm = 0;
            this.TotalSumm = 0;
            this.ChargeRate = 0;
            this.ChargeSumm = 0;
            this.IsReturn = @"N";
            this.LockStatus = false;
            this.TaxSumm = 0;
            OnCreated();
        }

        #region Properties

        public virtual decimal IdDoc { get; set; }

        public virtual decimal IdPriceType { get; set; }

        public virtual double DiscountRate { get; set; }

        public virtual double DiscountSumm { get; set; }

        public virtual double TotalSumm { get; set; }

        public virtual decimal IdSeller { get; set; }

        public virtual decimal IdCustomer { get; set; }

        public virtual decimal? IdDocReturn { get; set; }

        public virtual double ChargeRate { get; set; }

        public virtual double ChargeSumm { get; set; }

        public virtual string IsReturn { get; set; }

        public virtual bool LockStatus { get; set; }

        public virtual double TaxSumm { get; set; }

        public virtual decimal? IdSubdivision { get; set; }

        #endregion

        #region Navigation Properties

        public virtual DocJournal DocJournal { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
