//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt
{
    public partial class DocGoodsDetail
    {

        public DocGoodsDetail()
        {
            this.Quantity = 1;
            this.Price = 0;
            this.ItemQuantity = 1;
            this.DiscountRate = 0;
            this.DiscountSumm = 0;
            this.ChargeRate = 0;
            this.ChargeSumm = 0;
            this.LockStatus = false;
            this.Err = 0m;
            OnCreated();
        }

        #region Properties

        public virtual decimal IdDoc { get; set; }

        public virtual decimal IdGood { get; set; }

        public virtual int Quantity { get; set; }

        public virtual double Price { get; set; }

        public virtual decimal IdItem { get; set; }

        public virtual int ItemQuantity { get; set; }

        public virtual int? ItemPo { get; set; }

        public virtual double DiscountRate { get; set; }

        public virtual double DiscountSumm { get; set; }

        public virtual double ChargeRate { get; set; }

        public virtual double ChargeSumm { get; set; }

        public virtual bool LockStatus { get; set; }

        public virtual decimal? Err { get; set; }

        /// <summary>
        /// Себестоимость товара на момент добавления строки в документ.
        /// </summary>
        public virtual double? Prime { get; set; }

        #endregion

        #region Navigation Properties

        public virtual DocJournal DocJournal { get; set; }
        public virtual RefGood Good { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
