//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt
{
    public partial class DocJournal
    {

        public DocJournal()
        {
            this.IdInstanceSender = 1m;
            this.IdInstanceReciepient = 1m;
            this.IdInstanceOwner = 1m;
            this.ActStatus = 0;
            this.LockStatus = false;
            this.CreateInvoice = 0m;
            this.Deleted = 0m;
            this.UpdatedPrice = 0m;
            this.DocJournals = new List<DocJournal>();
            this.Details = new List<DocGoodsDetail>();
            this.DocGoodsDetailsIs = new List<DocGoodsDetailsI>();
            OnCreated();
        }

        #region Properties

        public virtual decimal Id { get; set; }

        public virtual string Code { get; set; }

        public virtual string Comment { get; set; }

        public virtual global::System.DateTime DocDatetime { get; set; }

        public virtual decimal IdDocType { get; set; }

        public virtual decimal? IdInstanceSender { get; set; }

        /// <summary>
        /// Регион-получатель для транзитного прихода
        /// </summary>
        public virtual decimal? IdInstanceReciepient { get; set; }

        public virtual decimal IdInstanceOwner { get; set; }

        public virtual decimal? IdDocMaster { get; set; }

        public virtual string ErrorStatus { get; set; }

        public virtual int ActStatus { get; set; }

        public virtual bool LockStatus { get; set; }

        public virtual string UserName { get; set; }

        public virtual decimal CreateInvoice { get; set; }

        public virtual global::System.DateTime? DeliveryDate { get; set; }

        public virtual decimal Deleted { get; set; }

        public virtual decimal? UpdatedPrice { get; set; }

        public virtual decimal? PayDelay { get; set; }

        #endregion

        #region Navigation Properties

        public virtual List<DocJournal> DocJournals { get; set; }
        public virtual DocJournal DocMaster { get; set; }
        public virtual List<DocGoodsDetail> Details { get; set; }
        public virtual DocGood DocGoods { get; set; }
        public virtual List<DocGoodsDetailsI> DocGoodsDetailsIs { get; set; }
        public virtual DocGoodsI DocGoodsI { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
