//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class DocLineItem
    {

        public DocLineItem()
        {
            OnCreated();
        }

        #region Properties

        public virtual string Id { get; set; }

        public virtual string IdOrder { get; set; }

        public virtual long? IdGood { get; set; }

        public virtual long? IdPriceType { get; set; }

        public virtual string IdDocJournal { get; set; }

        public virtual string Gtin { get; set; }

        public virtual string BuyerCode { get; set; }

        public virtual string Description { get; set; }

        public virtual string Amount { get; set; }

        public virtual string ReqQunatity { get; set; }

        public virtual string UnitOfMeasure { get; set; }

        public virtual string NetPrice { get; set; }

        public virtual string NetPriceVat { get; set; }

        public virtual string NetAmount { get; set; }

        public virtual string VatRate { get; set; }

        public virtual string VatAmount { get; set; }

        public virtual string RegionIsoCode { get; set; }

        public virtual string LineNumber { get; set; }

        public virtual string OrdrspNetPrice { get; set; }

        public virtual string OrdrspNetPriceVat { get; set; }

        public virtual string OrdrspNetAmount { get; set; }

        public virtual string OrdrspAmount { get; set; }

        public virtual string OrdrspQuantity { get; set; }

        public virtual string RecadvAcceptQuantity { get; set; }

        public virtual string RecadvAcceptNetPrice { get; set; }

        public virtual string RecadvAcceptNetPriceVat { get; set; }

        public virtual string RecadvAcceptAmount { get; set; }

        public virtual string RecadvAcceptNetAmount { get; set; }

        public virtual string Manufacturer { get; set; }

        public virtual string IsRemoved { get; set; }

        #endregion

        #region Navigation Properties

        public virtual DocOrder DocOrder { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
