//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class DocOrder
    {

        public DocOrder()
        {
            this.Status = 0;
            this.DocLineItems = new List<DocLineItem>();
            this.LogOrders = new List<LogOrder>();
            OnCreated();
        }

        #region Properties

        public virtual string Id { get; set; }

        public virtual string Number { get; set; }

		public virtual global::System.DateTime? OrderDate { get; set; }

		public virtual string DocType { get; set; }

        public virtual string IsTest { get; set; }

        public virtual global::System.DateTime? EdiCreationDate { get; set; }

        public virtual global::System.DateTime? EdiCreationSenderDate { get; set; }

        public virtual global::System.DateTime? ReqDeliveryDate { get; set; }

        public virtual string GlnSender { get; set; }

        public virtual string GlnSeller { get; set; }

        public virtual string GlnBuyer { get; set; }

        public virtual string GlnShipTo { get; set; }

        public virtual string Comment { get; set; }

        public virtual string CurrencyCode { get; set; }

        public virtual string TotalAmount { get; set; }

        public virtual string TotalVatAmount { get; set; }

        public virtual string TotalSumExcludeTax { get; set; }

        public virtual long Status { get; set; }

        #endregion

        #region Navigation Properties

        public virtual RefCompany ShipTo { get; set; }
        public virtual RefCompany Buyer { get; set; }
        public virtual RefCompany Seller { get; set; }
        public virtual RefCompany Sender { get; set; }
        public virtual List<DocLineItem> DocLineItems { get; set; }
        public virtual List<LogOrder> LogOrders { get; set; }
        public virtual RefOrderStatus RefOrderStatus { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
