//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class LogOrder
    {

        public LogOrder()
        {
            OnCreated();
        }

        #region Properties

        public virtual string Id { get; set; }

        public virtual string IdOrder { get; set; }

        public virtual long OrderStatus { get; set; }

        public virtual global::System.DateTime Datetime { get; set; }

        public virtual long? IdDocJournal { get; set; }

        public virtual string CircilationId { get; set; }

        public virtual string MessageId { get; set; }

        public virtual decimal? IdManufacturer { get; set; }

        #endregion

        #region Navigation Properties

        public virtual DocOrder DocOrder { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
