//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class MapPriceType
    {

        public MapPriceType()
        {
            OnCreated();
        }

        #region Properties

        public virtual string Id { get; set; }

        public virtual string GlnCompany { get; set; }

        public virtual decimal IdPriceType { get; set; }

        public virtual decimal? IdFilial { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
