//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt
{
    /// <summary>
    /// Справочник контрагентов (является предком для всех справочников, связанных с людьми ;-)
    /// </summary>
    public partial class RefContractor
    {

        public RefContractor()
        {
            this.IdDistrict = 80001m;
            OnCreated();
        }

        #region Properties

        public virtual decimal Id { get; set; }

        public virtual string Name { get; set; }

        /// <summary>
        /// Ссылка на справочник районов
        /// </summary>
        public virtual decimal? IdDistrict { get; set; }

        public virtual decimal? IdCity { get; set; }

        public virtual string Comment { get; set; }

        public virtual string Address { get; set; }

        public virtual string Phone { get; set; }

        public virtual string Contact { get; set; }

        public virtual decimal? DefaultCustomer { get; set; }

        public virtual decimal? IdChannel { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
