//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class RefCompany
    {

        public RefCompany()
        {
            this.MapPriceTypes = new List<MapPriceType>();
            this.ShipToOrders = new List<DocOrder>();
            this.BuyerOrder = new List<DocOrder>();
            this.SellerOrders = new List<DocOrder>();
            this.SenderOrders = new List<DocOrder>();
            this.Companies = new List<ViewRefFilial>();
            OnCreated();
        }

        #region Properties

        public virtual string Gln { get; set; }

        public virtual string Name { get; set; }

        public virtual string City { get; set; }

        public virtual long? IdContractor { get; set; }

        public virtual string Kpp { get; set; }

        public virtual string Inn { get; set; }

        public virtual string RegionCode { get; set; }

        public virtual string Street { get; set; }

        public virtual string House { get; set; }

        public virtual string Flat { get; set; }

        public virtual string PostalCode { get; set; }

        public virtual global::System.DateTime? LastSync { get; set; }

        public virtual string ParentGln { get; set; }

        public virtual long? IdDbFilial { get; set; }

        #endregion

        #region Navigation Properties

        public virtual List<MapPriceType> MapPriceTypes { get; set; }
        public virtual List<DocOrder> ShipToOrders { get; set; }
        public virtual List<DocOrder> BuyerOrder { get; set; }
        public virtual List<DocOrder> SellerOrders { get; set; }
        public virtual List<DocOrder> SenderOrders { get; set; }
        public virtual List<ViewRefFilial> Companies { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
