//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 01.10.2020 15:53:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Abt
{
    /// <summary>
    /// ??????? ????????? ??????
    /// </summary>
    public partial class RefItem
    {

        public RefItem()
        {
            this.Weight = 0m;
            this.Cbm = 0m;
            OnCreated();
        }

        #region Properties

        public virtual decimal Id { get; set; }

        public virtual decimal? IdGood { get; set; }

        public virtual decimal IdName { get; set; }

        public virtual int Quantity { get; set; }

        public virtual decimal Weight { get; set; }

        public virtual decimal Cbm { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
