//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:35:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class ViewRefFilial
    {

        public ViewRefFilial()
        {
            OnCreated();
        }

        #region Properties

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Link { get; set; }

        public virtual string Ip { get; set; }

        #endregion

        #region Navigation Properties

        public virtual RefCompany Filials { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
