//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 05.10.2020 13:32:16
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace DataContextManagementUnit.DataAccess.Contexts.Edi
{
    public partial class ViewInvoicHead
    {

        public ViewInvoicHead()
        {
            OnCreated();
        }

		#region Properties

		public virtual decimal Id { get; set; }
		public virtual string Barcode { get; set; }
        public virtual decimal SellerId { get; set; }
        public virtual string SellerName { get; set; }
        public virtual string SellerFullName { get; set; }
        public virtual string SellerAddress { get; set; }
        public virtual string SellerInn { get; set; }
        public virtual string SellerPhone { get; set; }
        public virtual string Director { get; set; }
        public virtual string Accountant { get; set; }
        public virtual decimal? OldNdp { get; set; }
        public virtual string SellerKpp { get; set; }
        public virtual string SellerOkpo { get; set; }
        public virtual string SellerPostalAddress { get; set; }
        public virtual string SellerCity { get; set; }
        public virtual string SellerAccount { get; set; }
        public virtual string SellerCorAccount { get; set; }
        public virtual string SellerBankName { get; set; }
		public virtual decimal CustomerId { get; set; }
		public virtual string CustomerBankName { get; set; }
        public virtual string CustomerBankCity { get; set; }
        public virtual string SellerBankCity { get; set; }
        public virtual string SellerBankSwift { get; set; }
        public virtual string CustomerName { get; set; }
        public virtual string Dogovor { get; set; }
        public virtual string NameGp { get; set; }
        public virtual string JuridicalAddress { get; set; }
        public virtual string CustomerInn { get; set; }
        public virtual string CustomerPhone { get; set; }
        public virtual string CustomerKpp { get; set; }
        public virtual string PostalAddress { get; set; }
        public virtual string CustomerCity { get; set; }
        public virtual string CustomerAccount { get; set; }
        public virtual string CustomerCorAccount { get; set; }
        public virtual string CustomerBankSwift { get; set; }
        public virtual string CustomerOkpo { get; set; }
        public virtual global::System.DateTime? DocDatetime { get; set; }
        public virtual string Code { get; set; }
        public virtual double TotalSumm { get; set; }
        public virtual double TaxSumm { get; set; }
        public virtual string TotalSummText { get; set; }
        public virtual string TotalCount { get; set; }
        public virtual decimal? PayDelay { get; set; }
        public virtual global::System.DateTime? DeliveryDate { get; set; }
        public virtual string Storekeeper { get; set; }
		public virtual string StorekeeperProf { get; set; }
		public virtual string ZCode { get; set; }
        public virtual string Comment { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
